version: '3'
services:
  app:
    container_name: app
    hostname: app
    build:
      context: ./app
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ./../src/:/go/src/work
